#
# LuaDist Travis-CI Hook
#

# Since CMake is not directly supported we use erlang VMs
language: C

# We need CMake and LuaDist
install:
  - sudo apt-get install cmake >/dev/null 2>&1

# Run the lazy install one-liner
script:
  - echo "$(curl -fksSL https://raw.github.com/gist/2394281/luadist.sh)" | bash

# Execute additional tests or commands
after_script:
  - LuaDist-batteries/bin/luadist list

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
