#
# LuaDist Travis-CI Hook
#

# Use VMs for C
language: C

# We need CMake
install:
  - sudo apt-get -qq install cmake >/dev/null 2>&1

# Make sure installing works
script:
  - ./install lua

# List bootstrap modules
after_script:
  - _install/bin/luadist list

# Only watch the master branch
branches:
  only:
    - master

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
